# Generated by Django 4.1 on 2022-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
